### PR TITLE
Introduce Whiskers to the template

### PR DESCRIPTION
**Pull request by unseen-ninja**
This adds the relevant folders as well as a very simple example config.

### CODE REVIEW

**Comment by sgoudham** [comment]
I'd personally like if we fleshed out whiskers more (e.g. to handle single files and multiple) before introducing it to new developers that would be cloning this template.

I've got a PR ready to be reviewed here: https://github.com/catppuccin/toolbox/pull/111 and currently working on writing up the content in the RFC: https://github.com/catppuccin/community/pull/12

**Comment by unseen-ninja** [comment]
Oh yeh, I agree!
I just figured I may take the current state of it and draft up a PR since this is probably one of the more important repos we have. It's more or less just another status indicator. I've sadly not been following the conversation too closely, but it seems like there are a couple things to figure out before Whiskers is what it's supposed to be.

I *should* should have marked this as a draft as well.. Done now! (and shouldn't throw out PRs without the brain capacity to also type out a clear description) :D

**Comment by Anomalocaridid** [comment]
With the [recent announcement officially unveiling whiskers](https://github.com/catppuccin/community/discussions/15), would now be a good time to add whiskers to this template? Of course, this PR would need to be updated to account for changes since then.

**Comment by unseen-ninja** [comment]
Yeah, that's something I've thought about as well. I wanted to take some time to maybe make a template file that explains things a little better since the tera rewrite changed quite a few things. Afaik Whiskers also has some outstanding things that may need no be considered – @backwardspy @sgoudham @nullishamy?

**Comment by backwardspy** [comment]
> Afaik Whiskers also has some outstanding things that may need no be considered

there are some enhancements to be made but it shouldn't change things too much. the main one i want to fix is the ability to reference colours directly by name when rendering with `flavor` in the matrix. that'll be relevant if you want to use a matrix in this template example.

before:
```
---
whiskers:
    version: "2.0"
    matrix:
    - flavor
----
{% set palette = flavor.colors %}
{{palette.red.hex}}
```

after:
```
---
whiskers:
    version: "2.0"
    matrix:
    - flavor
----
{{red.hex}}
```

**Comment by sgoudham** [comment]
Closing this, see https://github.com/catppuccin/template/pull/11#issuecomment-2130541990 for an explanation as to why.

**Pull request closed without merging**
